### ISSUE TITLE
image build pipeline steps failing with OOMKilled

### ISSUE THREAD

**Issue by erikerlandson** [AICoE/aicoe-ci#130]
**Describe the bug**
trying to run an image build:
https://github.com/thoth-station/ray-ml-worker/issues/11

The build pipeline task is running out of memory
```
terminated:
  containerID: 'cri-o://c3c717be8b69f79fb115c3db81bd3857d1c66166cab30b47b958c166c326f961'
  exitCode: 0
  finishedAt: '2021-08-18T13:48:40Z'
  reason: OOMKilled
  startedAt: '2021-08-18T13:43:52Z'
```

**To Reproduce**
Build the pipeline as described in the above 'deliver image build' issue
The pipeline should fail in the image build step with `OOMKilled`

**Expected behavior**
Builds requiring more memory should run to completion
