### ISSUE TITLE
onboarding-issue-task will need to be updated with latest opfcli changes

### ISSUE THREAD

**Issue by Gregory-Pereira** [AICoE/aicoe-ci#169]
with changes going to be introduced in [opfcli pr 44 (onboard)](https://github.com/operate-first/opfcli/pull/44), the [onboarding task](https://github.com/AICoE/aicoe-ci/blob/master/tasks/onboarding-issue-task.yaml) will need to get updated. To understand the parsing that will need to happen look any of the sample configs provided in testdata of the opfcli, ex:
```
env: MOC
namespaces:
  - enable_monitoring: false
    name: testproject
    quota: testquota
    custom_quota:
      limits.cpu: '28'
      requests.cpu: '28'
      limits.memory: 32Gi
      requests.memory: 32Gi
      limits.storage: 200Gi
      requests.storage: 100Gi
      count/objectbucketclaims.objectbucket.io: 1
project_description: This is the configuration for a sample project / app to onboard
target_cluster: Smaug
team_name: testgroup
users:
  - testing_gh_handle_1
  - testing_gh_handle_2
```
Something like this should be generated as result of the end result of the task. Note that all `custom_quota` values as well as `custom_quota` itself, `users`, `target_cluster` and `quota` are all optional.

/assign
